spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nbc?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: deposit
    password: Vision@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: f9130887a39c39
    password: c7e9063e90c1ae
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          ssl:
            trust: smtp.mailtrap.io
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  http:
    multipart:
      enabled: true
  #banner:
  #  location: banner.txt
server:
  port: 8686
springdoc:
  api-docs:
    path: /int/api